### ISSUE TITLE
_footer.scss doesn't have right markup

### ISSUE THREAD

**Issue by tariqinaam** [thoughtbot/refills#320]
I copied mega footer markup from refill. But it doesnt seem right.
It add 80% margin-left on .footer-links class in desktop view. Not exactly sure how.
![desctop screenshot](https://cloud.githubusercontent.com/assets/3472479/8627847/cae2ca2a-2745-11e5-8afd-4fedfdef5a1e.png)

**Comment by vga-** [comment]
Did you ever figure this one out? I'm having the same issue but it wasn't 80%, its was about 35%. This pushed the columns too far to the right. I'm using lib-sass, node-neat, and bitters.

**Comment by vga-** [comment]
This has something to do with:

```scss
.footer-links {
  @include clearfix;
  margin-bottom: $base-spacing;

  @include media($medium-screen) {
    @include shift(3);
  }
}
```

If I change the shift to 2.4 it looks fine. Is there some known issue with shift?
