### ISSUE TITLE
Does tabs CSS need the `.is-open` class?

### ISSUE THREAD

**Issue by tute** [thoughtbot/refills#384]
I copied over the code for the tabs from http://refills.bourbon.io/, but I needed to add the following for content to show up:

```scss
  .tab-content {
    // ...

    &.is-open {
      display: block;
    }
  }
```

Is it missing in the snippets, or am I using this incorrectly? Thank you! :)
